.maestro/config.yaml, .maestro/onboarding/walletImportUsingPrivateKey.yaml
closes [#2676](https://github.com/vechain/veworld-mobile/issues/2676)
https://github.com/user-attachments/assets/07675df3-202d-430f-90ff-a08054347cd6
https://github.com/user-attachments/assets/145ac238-6ce4-44f3-aaf5-cb2ace73192d
added a new scenario for importing local wallet using private key
@Doublemme
=> refactor: adding scenario for wallet import using private key

src/Screens/Flows/App/AssetDetailScreen/Components/ConvertBetterBottomSheet.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/ConvertBetterCard.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/VbdBalanceCard.tsx
If user hasn't any vot3 or b3tr when opens the token details page app was crashing, handled the situation on the  convert bottom sheet that is creating the error
@grenos @mfrezzati
https://github.com/user-attachments/assets/d952d2b5-e754-414d-90cc-8071ca17c0b4
---
=> Fix: App crash when openin VBD details page

src/Screens/Flows/App/ActivityScreen/Components/ActivityBox.tsx, src/Screens/Flows/App/ActivityScreen/Components/ActivitySectionList.tsx
Closes #
- Correct formatting for addresses added
- Current year no longer displayed in activity header
@grenos @Doublemme @mfrezzati
---
=> fix: format addresses and current year is not shown anymore

src/Screens/Flows/App/AddContactScreen/AddContactScreen.tsx
Updated the form validator and changed the submit button color when creating a contact
@mfrezzati
https://github.com/user-attachments/assets/c5d94848-d183-406e-8552-f71bc5371c63
---
=> Fix: false disabled contact button

src/Navigation/Stacks/HomeStack.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/ConvertBetterBottomSheet.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/ConvertBetterCard.tsx, src/Screens/Flows/App/AssetDetailScreen/ConvertBetterScreen/Components/ConvertBetterTokenSuccessBottomSheet.tsx, src/Screens/Flows/App/AssetDetailScreen/ConvertBetterScreen/Components/TransferTokenCard.tsx, src/Screens/Flows/App/AssetDetailScreen/ConvertBetterScreen/ConvertTransactionScreen.tsx
Changed token types and fixed font weight param causing app crash
@mfrezzati
[fix_crash_app.webm](https://github.com/user-attachments/assets/e2673834-dfab-4aae-a512-db6804118a45)
---
=> Fix: Covert better tokens on android

src/Components/Reusable/BottomSheets/QRCodeBottomSheet/QRCodeBottomSheet.tsx, src/Screens/Flows/App/ClaimUsername/UsernameClaimed.tsx
Fixes vechain/veworld-private#26
Removed the user ref for storing the account address
@mfrezzati
https://github.com/user-attachments/assets/506562a5-dc8c-4ff1-b3bb-9d4c8667ea1c
---
=> 2751 Fix copy and shown address on receive modal

src/Screens/Flows/App/ActivityScreen/Components/ActivityBox.tsx, src/Utils/TransactionUtils/TransactionUtils.spec.ts, src/Utils/TransactionUtils/TransactionUtils.ts
Closes #2753 
Closes #
@grenos @Doublemme @mfrezzati
https://github.com/user-attachments/assets/9d06f2df-121b-47a2-a8b6-8c0ccd9dac3d
---
=> fix: handled swap activities with 1 event to avoid sapp crash

.maestro/onboarding/walletImportUsingKeystoreFile.yaml, .maestro/userActivity/userActivity.yaml
Closes #2677 
added scenario for wallet import using keystore file
@Doublemme
=> refactor: adding scenario for wallet import using keystore file

android/app/build.gradle, package.json
Closes #2771
- Do not remove yarn.lock in FastLane commands to avoid unexpected behaviors in testing
- Add liblog.so to packagingOptions on Android build to compile on x86 Windows PC
- Add lint-staged as a separate yarn command to avoid issues with the .bin folder
@grenos @Doublemme @mfrezzati
---
=> chore: update Windows tooling

src/Api/Coingecko/hooks.ts, src/Components/Reusable/Tokens/OfficialTokenCard.tsx, src/Screens/Flows/App/AssetDetailScreen/AssetDetailScreen.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/AssetChart.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/ChartView.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/VbdBalanceCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/TokenList.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/VeB3trTokenCard.tsx
Fixes vechain/veworld-private#55
Temporary switched the endpoint where we get the exchange rate for B3TR from Coingecko to VechainStats
@hughlivingstone @HiiiiD 
<image width="380" src="https://github.com/user-attachments/assets/4983df14-12f5-4c62-9ea1-7ef77bcc5ff1"/>
<image width="380" src="https://github.com/user-attachments/assets/c1c4b7b8-f5bb-4e92-ae2e-4d9886564bae"/>
<image width="380" src="https://github.com/user-attachments/assets/33289f1a-8c96-44f5-ac33-3dd9e6d3e8bf" />
---
=> Fix: temporary removed fetch better tokens price from coingecko

ios/Podfile.lock, ios/VeWorld.xcodeproj/project.pbxproj, package.json, yarn.lock
Fixes vechain/veworld-private#53
Fixed library version for BLE `react-native-ble-plx` that is a dependency of `@ledgerhq/react-native-hw-transport-ble` and required the version fixed to `3.2.1`
@hughlivingstone @HiiiiD @paolampilla 
https://github.com/user-attachments/assets/4735e49e-850e-4788-b354-a2fd54103551
---
=> 53 Fix :: Ledger not working RN 0.74

src/Screens/Flows/App/SendScreen/01-SelectTokenSendScreen/01-SelectTokenSendScreen.tsx
fixes the address check for VOT3 in the send flow, making the bottom sheet pop up correctly
@HiiiiD  @Doublemme @hughlivingstone 
---
=> fix: vote send bottom sheet

src/Screens/Flows/App/ActivityScreen/Components/ActivityBox.tsx
The description of an activity looks a little bit smaller from the design so I'll increased it by 2px 
@HiiiiD @hughlivingstone @paolampilla 
---
=> Fix :: increased font size in activity box

src/Screens/Flows/App/ActivityScreen/Components/ActivityBox.tsx, src/Storage/Redux/Helpers.ts, src/Storage/Redux/Migrations/Migration12.ts, src/Storage/Redux/Migrations/index.ts, src/Storage/Redux/Selectors/Activity.ts, src/Storage/Redux/Slices/Activity.ts
Closes vechain/veworld-private#65
- Created a new storage migration for remove duplicate entries in the local activity with the same ids and keep the recent one. 
- Fixed how we add a new local tx, in details we moved from an INSERT method to UPSERT method
- Removed the truncate of the NFT description 
@HiiiiD @hughlivingstone @paolampilla 
https://github.com/user-attachments/assets/42889c07-82d8-47e8-bfbf-c37416a70091
---
=> 65 Activity page perf issues

.github/workflows/e2e-android.yml, .github/workflows/e2e-ios.yml, .maestro/onboarding/createNewWalletAndBackupMnemonic.yaml, .maestro/onboarding/walletImportUsingKeystoreFile.yaml, .maestro/onboarding/walletImportUsingPrivateKey.yaml, .maestro/send/send_custom_token_delegation.yaml, .maestro/send/send_tokens_account_method.yaml, .maestro/send/send_vet_vetho.yaml, .maestro/userActivity/userActivity.yaml
Closes #2782 
This change ensures that tests tagged with `pull-request` will be executed in the CI pipeline for both iOS and Android platforms whenever a pull request is created or updated. 
This helps in:
- Running relevant tests during the PR review process
- Maintaining platform-specific test exclusions (tests tagged with `onlyAndroid` won't run on iOS and vice versa)
- Automating the testing process for pull requests
- The changes have been tested locally
- The workflow modifications maintain existing platform-specific exclusions
- The changes are compatible with the existing CI pipeline structure
- No breaking changes
- Improves CI/CD process by ensuring pull request tests are executed
- Maintains existing test coverage and platform-specific test configurations
- Part of the ongoing …
=> feat: add pull-request tag to E2E test workflows for CI

android/app/build.gradle
Fix the check for the application signature.  This should look in the correct location for the release.keystore when built in CI.
@Doublemme
N/A
---
=> fix: directory to look for signing key for release build

src/Components/Base/BaseSpacer.tsx, src/Components/Base/BaseText.tsx, src/Components/Base/BaseView.tsx, src/Screens/Flows/App/ActivityScreen/Components/ActivityBox.tsx
Closes #
- Make sure long names fit correctly
- Fix received tokens from/to
@Doublemme
---
=> fix: make containers fit correctly + fix ui bug

src/Components/Reusable/SwapCard/Components/TokenBox.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/ConvertedBetterBottomSheet.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/BaseTokenCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/TokenCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/VeB3trTokenCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/VechainTokenCard.tsx
Closes [UI Bugs](https://github.com/vechain/veworld-private/issues/81)
@Doublemme @hughlivingstone @HiiiiD 
---
=> 81 UI bugs   212

README.md
Added RN 0.74 migration guide
@grenos
-   [x] Documentation, if applicable, has been updated.
---
=> Add React Native 0.74 migration guide in readme

.github/workflows/generate-translations.yml, package.json
Closes vechain/veworld-private#90
Add workflow to automatically create translations
@Doublemme @hughlivingstone 
---
=> feat: create generate translations workflow file

.github/workflows/generate-translations.yml
Closes #
- Provide a name to the workflow
- Allow empty commit
- Clear all translations before generating new ones
@Doublemme @hughlivingstone 
---
=> Fix Translations pipeline

src/Storage/Redux/Slices/Browser.ts
Closes #
Fix visited urls hooks
---
=> fix: fix visited urls

.github/workflows/e2e-ios.yml
Closes # 106
force github runner to Macos V15
@BenMVeChain 
none, ci/cd only
---
=> fix: fix build runner by setting to MacOs V15 (#106)

src/Components/Reusable/FavoriteDAppCard/FavoriteDAppCard.tsx, src/Components/Reusable/Spinner/Spinner.tsx, src/Components/Reusable/Spinner/Stroke.tsx, src/Hooks/useBrowserSearch/useBrowserSearch.spec.ts, src/Hooks/useBrowserSearch/useBrowserSearch.ts, src/Hooks/useDappsWithPagination/useAppHubDapps.ts, src/Hooks/useDappsWithPagination/useDappsWithPagination.ts, src/Screens/Flows/App/DiscoverScreen/Components/DAppCard.tsx, src/Screens/Flows/App/DiscoverScreen/Components/DAppHorizontalCard.tsx, src/Screens/Flows/App/DiscoverScreen/Components/DAppsLoadingSkeleton.tsx, src/Screens/Flows/App/DiscoverScreen/Components/Favourites.tsx, src/Screens/Flows/App/DiscoverScreen/Components/PopularTrendingDApps.tsx, src/Screens/Flows/App/DiscoverScreen/Components/SearchBar.tsx, src/Screens/Flows/App/DiscoverScreen/Components/SearchResultItem.spec.tsx, src/Screens/Flows/App/DiscoverScreen/Components/SearchResultItem.tsx, src/Screens/Flows/App/DiscoverScreen/Components/SearchResults.tsx, src/Screens/Flows/App/DiscoverScreen/SearchScreen.tsx, src/Screens/ResetAppScreen.tsx
Closes vechain/veworld-private#107
- Reduce trending dapps to 10
- Remove sustainability tag
@Doublemme @paolampilla 
---
=> Reduce trending dapps to 10 + remove sustainability tag

src/Api/FeatureFlags/endpoint.ts, src/AppLoader.tsx, src/Components/Providers/FeatureFlagsProvider.tsx
Add feature flag to App Loader logging
@Doublemme
---
=> chore: add debug feature flag

src/Api/FeatureFlags/endpoint.ts, src/AppLoader.tsx, src/Components/Providers/FeatureFlagsProvider.tsx
Unmount the app loader component when app is not loading
@Doublemme
---
=> Refactor: App loader

src/Components/Base/BaseBottomSheet.tsx
Closes #
Remove blur backdrop on Android
@Doublemme @paolampilla 
---
=> Remove blur backdrop on Android

src/Components/Base/BaseCarousel/BaseCarousel.tsx, src/Components/Base/BaseCarousel/BaseCarouselItem.tsx, src/Screens/Flows/App/DiscoverScreen/Components/VeBetterDAOCarousel.tsx
Closes vechain/veworld-private#121
Disabled the autoplay and the loop effect to adjust following the layout
https://github.com/user-attachments/assets/36c8a02f-587d-4866-94ed-adb397e0dbdd
---
=> 121 Removed autoplay from discovery banners

src/Screens/Flows/App/HomeScreen/HomeScreen.tsx, src/Screens/Flows/App/HomeScreen/Hooks/useTokenBalances.tsx
Cleared cache and updated suggested tokens logic
@HiiiiD 
N/A
---
=> Fix: improve veDelegate balance handling in HomeScreen

src/Components/Reusable/Network/NetworkBox/NetworkBox.tsx, src/Screens/Flows/App/ManageCustomNodesScreen/ManageCustomNodesScreen.tsx, src/Screens/Flows/App/NetworkScreen/Components/CustomNodes.spec.tsx, src/Screens/Flows/App/NetworkScreen/Components/CustomNodes.tsx
Updated the the screens accordingly with the latest design changes
https://github.com/user-attachments/assets/505ab669-faec-4198-80ed-720f4f862279
---
=> Refactor: manage node screen layout and improve custom nodes components

src/Constants/Constants/Thor/abis/VeBetterDao.abi.ts, src/Hooks/VeBetterDao/useCurrentAllocationRoundId.ts, src/Hooks/VeBetterDao/useRoundXApps.ts, src/Hooks/VeBetterDao/useXAppsShares.ts, src/Hooks/useDappsWithPagination/useAppHubDapps.spec.ts, src/Hooks/useDappsWithPagination/useAppHubDapps.ts, src/Hooks/useFetchFeaturedDApps/index.ts, src/Hooks/useFetchFeaturedDApps/useVeBetterDaoActiveApps.ts, src/Hooks/useFetchFeaturedDApps/useVeBetterDaoDapps.ts, src/Hooks/useNewDApps/useNewDApps.spec.ts, src/Hooks/useNewDApps/useNewDApps.ts, src/Hooks/useThorClient/useThorClient.ts, src/Hooks/useTransactionScreen/useTransactionScreen.tsx, src/Hooks/useTrendingDApps/useTrendingDApps.spec.ts, src/Networking/DApps/getVeBetterDaoDApps.ts, src/Storage/Redux/Selectors/Network.ts
Closes vechain/veworld-private#128
Show all VBD apps (included the ones not active) everywhere, except for:
- New Dapps
- Trending Dapps
- Sustainability filter on Ecosystem section
@Doublemme
[updated_dapps.webm](https://github.com/user-attachments/assets/3f1aa56f-1de7-420f-b6ce-539da9b9a1c2)
---
=> 128 bug   dapps that lost endorsement dont have names in activity

src/i18n/formatters.ts
Closes vechain/veworld-private#139
Add formatters for Chinese and Taiwanese
@Doublemme
---
=> fix: fix langs

.github/workflows/create-release-pr.yml
Closes #
add workflow dispatch and use app in create-release-pr
---
=> fix: add workflow dispatch and use app in create-release-pr

package.json, src/Hooks/useTotalTokenBalance/useTotalTokenBalance.ts, src/Networking/FungibleToken/FungibleTokenNetworking.ts, src/Screens/Flows/App/AssetDetailScreen/BridgeAssetDetailScreen.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/BalanceView.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/BridgeTokenBalanceCard.spec.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/BridgeTokenCard.tsx, src/Screens/Flows/App/ManageCustomTokenScreen/BottomSheets/AddCustomTokenBottomSheet/AddCustomTokenBottomSheet.tsx, src/Screens/Flows/App/SendScreen/02-SelectAmountSendScreen/02-SelectAmountSendScreen.tsx, src/Storage/Redux/Helpers.ts, src/Storage/Redux/Migrations/Migration17.ts, src/Storage/Redux/Migrations/index.ts, src/Test/helpers/data/tokens.ts, src/Utils/BigNumberUtils/BigNumberUtils.ts, src/Utils/polyfill/index.ts, yarn.lock
Closes vechain/veworld-private#140
@Doublemme
---
=> 140 enhancement   rounding strategy

.github/workflows/sync-release-info-to-s3.yml
=> Fix sync s3 worflow

src/Components/Providers/StoreProvider.tsx, src/Storage/Redux/Helpers.ts, src/Storage/Redux/Migrations/Migration18.ts, src/Storage/Redux/Migrations/index.ts
Closes #
rollback migration 18 -> 17
@HiiiiD @Doublemme 
---
=> fix: redux migration app crash

android/gradle.properties, src/Components/Base/BaseBottomSheet.tsx, src/Screens/Flows/App/NetworkScreen/Components/SelectNetwork/SelectNetworkBottomSheet.tsx
Reverts vechain/veworld-mobile#2989
=> Revert "FIX: First round of fixes"

src/Hooks/useTransactionScreen/useTransactionScreen.spec.ts, src/Hooks/useTransactionScreen/useTransactionScreen.tsx
Closes vechain/veworld-private#163
---
=> Convert `value` of a Clause to an hexadecimal string

src/Components/Reusable/Banners/StargateBannerClosable.tsx, src/Components/Reusable/Banners/StargateStakingBanner.tsx, src/Screens/Flows/App/ActivityScreen/Components/ActivitySectionList.tsx, src/Screens/Flows/App/DiscoverScreen/Components/Banners/StargateBanner.tsx, src/Screens/Flows/App/DiscoverScreen/Components/Banners/StellaPayBanner.tsx, src/Screens/Flows/App/DiscoverScreen/Components/Banners/VeBetterDaoBanner.tsx
Fixed banners font size and weight
@HiiiiD 
---
=> Fix :: Banners font size and font weight

src/Navigation/Stacks/HistoryStack.tsx
Fix navigation logic
https://github.com/user-attachments/assets/96e3bbdd-7a54-4732-a204-5e0a0b5b2423
---
=> Fix :: HistoryStack navigation

src/Components/Providers/InAppBrowserProvider/InAppBrowserProvider.tsx
Closes vechain/veworld-private#175
Reset visibility state of top and bottom bars inside InApp browser
https://github.com/user-attachments/assets/93ec45d2-eb46-4df1-ad3c-4fdbabf3b8c5
---
=> 175 - Reset Top and Bottom bars inside InAppBrowser

.github/workflows/create-release-pr.yml
Remove trailing comma
Add full path to key
@HiiiiD 
---
=> Fix: Remove trailing comma

.github/workflows/generate-version-translations.yml
=> Chore: Update id token config

.github/workflows/update-vercel.yaml
Closes #3011 
allow selection of apk for vercel push
---
=> fix: cicd: vercel upload should allow artifact source choice

src/Components/Reusable/SelectedNetworkViewer/SelectedNetworkViewer.spec.tsx, src/Storage/Redux/Slices/Notification.ts
Closes #2878 
Fixed the store migration to automatically enable and subscribe to all the dApps if user enable it
https://github.com/user-attachments/assets/b2cf23ab-ce53-49e5-8cec-ce6786faba47
---
=> Fix :: Enable dApp notifications by default

src/Components/Providers/InAppBrowserProvider/Components/CertificateBottomSheet/CertificateBottomSheet.tsx, src/Components/Providers/InAppBrowserProvider/Components/ConnectBottomSheet/ConnectBottomSheet.tsx, src/Screens/Flows/App/SendScreen/04-TransactionSummarySendScreen/04-TransactionSummarySendScreen.tsx, src/Screens/Flows/App/SendScreen/04-TransactionSummarySendScreen/TransactionSummarySendScreen.spec.tsx, src/Utils/BigNumberUtils/BigNumberUtils.ts
Closes #
Fix generic delegator fallback on send screen
Fix spacing on Connect Bottom Sheet and Certificate Bottom Sheet
---
=> fix: fix generic delegator fallback on send screen + spacing on new bs

src/Components/Providers/NotificationsProvider/NotificationsProvider.tsx
Moved the logic for keep the dapps tag in sync after OneSignal is initialized in order to avoid app crash
@HiiiiD 
N/A
---
=> Fix :: App crash due to OneSignal init

src/Hooks/useIsEnoughGas/useIsEnoughGas.spec.ts, src/Hooks/useIsEnoughGas/useIsEnoughGas.ts, src/Utils/BigNumberUtils/BigNumberUtils.ts
Closes #
Make sure to check if the remaining value is >= 0.
Use case: user with exactly 0 VTHO, when delegating, won't be able to send a transaction
---
=> fix: fix useIsEnoughGas to check for exact 0

src/Hooks/useCheckAppVersion/useCheckAppVersion.tsx
Closes #
Added loading state to prevent prompt decision version checking logic completes
---
=> fix: upgrade modal popup

.github/workflows/e2e-android.yml, .github/workflows/e2e-ios.yml
cicd workflow
Closes #
remove breaking debug message 
@HiiiiD @grenos @Doublemme 
---
=> ci: devicecloud remove breaking debug message

src/Components/Base/BaseCarousel/BaseCarousel.tsx, src/Components/Reusable/Staking/StargateLockedValue.tsx, src/Screens/Flows/App/ManageCustomTokenScreen/BottomSheets/AddCustomTokenBottomSheet/AddCustomTokenBottomSheet.tsx, src/Screens/Flows/App/ManageTokenScreen/ManageTokenScreen.tsx
Closes #
- Fix balance of Stargate when using comma
- Fix snapping of BaseCarousel
- Fix issue with balances that causes flaky e2e tests
@Doublemme
---
=> fix: fix comma + snap of base carousel

src/Components/Reusable/InAppBrowser/BrowserBottomBar.tsx, src/Constants/Enums/AnalyticsEvent.ts
Added navigation events when the user click `goBack` or `goForward` inside the InAppBrowser to have some metrics about the usage of them
N/A
---
=> Add browser navigation mixpanel events 

src/Components/Providers/InAppBrowserProvider/Components/CertificateBottomSheet/CertificateBottomSheet.tsx, src/Components/Reusable/DelegationOptions/SelectDelegationAccountBottomSheet/SelectDelegationAccountBottomSheet.tsx, src/Components/Reusable/SelectAccountBottomSheet/SelectAccountBottomSheet.tsx, src/Screens/Flows/App/ActivityScreen/ActivityScreen.tsx, src/Screens/Flows/App/HomeScreen/HomeScreen.tsx, src/Screens/Flows/App/SwapScreen/SwapScreen.tsx
Closes # https://github.com/vechain/veworld-private/issues/194
Replace the old wallet switcher component with the new one
---
=> [ Enhance ] - use new wallet switcher component app wide.

src/Screens/Flows/App/AssetDetailScreen/Components/StargateCarouselItem.tsx, src/Screens/Flows/App/HomeScreen/Components/BannerCarousel/BannersCarousel.tsx, src/Screens/Flows/App/HomeScreen/Components/Staking/StakedCard.tsx, src/Screens/Flows/App/HomeScreen/HomeScreen.tsx
Closes vechain/veworld-private#223
---
=> 223 bug   change padding for stargate

android/build.gradle
Google requires as targetSdkVersion 35, bumped it
N/A
---
=> chore: update android targetSdkVersion to 35

src/Components/Providers/InAppBrowserProvider/Components/CertificateBottomSheet/CertificateBottomSheet.tsx, src/Components/Providers/InAppBrowserProvider/Components/TransactionBottomSheet/TransactionBottomSheet.tsx, src/Components/Providers/InAppBrowserProvider/Components/TypedDataBottomSheet/TypedDataBottomSheet.tsx
Fixed the margin bottom on the new intraction bottomsheets
---
=> Fix :: Bottomsheets margin bottom

CHANGELOG.md, android/app/build.gradle, ios/VeWorld.xcodeproj/project.pbxproj, ios/VeWorld/Info.plist, ios/VeWorldTests/Info.plist, package.json
Reverts vechain/veworld-mobile#3141
=> Revert "version: build artifacts version-2.3.1 [iOS]"

.github/workflows/release-ios.yml
Closes #
- Fix Github runners
---
=> chore: try switching to macos14 with xcode 16.2

src/Components/Reusable/Staking/StargateLockedValue.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/BalanceView.tsx, src/Screens/Flows/App/AssetDetailScreen/Components/VbdBalanceCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/BaseTokenCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/BridgeTokenCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/TokenCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/VeB3trTokenCard.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/VechainTokenCard.tsx
=> fix: fix font sizes

.github/workflows/e2e-ios.yml, .github/workflows/install-build-test-scan.yml, .github/workflows/unit-tests.yml
Closes #
backport of Marco S build fix 
=> ci: backport MarcoS fix to e2e

src/Hooks/useFetchFeaturedDApps/useVeBetterDaoDapps.ts
Closes #
Fix an issue with cached values causing a crash
---
=> fix: fix app logo

.github/workflows/install-build-test-scan.yml, .maestro/config.yaml
=> Add E2E tests on schedule + remove broken Android test

src/Components/Reusable/InAppBrowser/BrowserBottomSheet.tsx, src/Constants/Theme/Colors.ts, src/Screens/Flows/App/AppsScreen/Components/Common/VbdCarousel/VbdCarouselBottomSheet.tsx, src/Screens/Flows/App/AppsScreen/Components/Common/VbdCarousel/VbdCarouselItem.tsx, src/Screens/Flows/App/AppsScreen/Components/FavoritesBottomSheet.tsx, src/Screens/Flows/App/AppsScreen/Components/SearchBar.tsx, src/Screens/Flows/App/AppsScreen/Components/SearchResultItem.spec.tsx, src/Screens/Flows/App/AppsScreen/Components/SearchResultItem.tsx, src/Screens/Flows/App/AppsScreen/Components/SearchResults.tsx
Closes vechain/veworld-private#279
---
=> 279 - Fix Search screen, Browser BS styles and App preview blur

src/Components/Base/BaseCarousel/BaseCarousel.tsx, src/Components/Base/BaseCarousel/FullscreenBaseCarousel.tsx, src/Components/Providers/InAppBrowserProvider/Components/TransactionBottomSheet/TransactionDetails.tsx
Closes #
Fix Transaction bottomsheet padding + pagination
---
=> Fix transaction bottomsheet

src/Screens/Flows/App/SettingsScreen/SettingsScreen.tsx
Reverts vechain/veworld-mobile#3222
=> Revert "284 - Removed header from settings page"

src/Screens/Flows/App/AppsScreen/Components/VeBetter/RowExpandableDetails.tsx
Closes #
Button text alignment
---
=> style: button alignment X2E bottomsheet

jest.setup.ts, src/Components/Base/BaseCarousel/BaseCarousel.tsx, src/Components/Base/BaseCarousel/BaseCarouselItem.spec.tsx, src/Components/Base/BaseCustomTokenIcon/BaseCustomTokenIcon.spec.tsx, src/Components/Base/BaseIcon.tsx, src/Hooks/useDelegation/useDelegation.spec.ts, src/Hooks/useTransactionFees/useGalacticaFees.spec.ts, src/Hooks/useTransactionFees/useTransactionFees.spec.ts, src/Hooks/useTransactionScreen/useTransactionScreen.spec.ts, src/Screens/Flows/App/AppsScreen/Components/SearchBar.spec.tsx, src/Screens/Flows/App/WalletManagement/WalletManagementScreen/hooks/useWalletDeletion.spec.ts
Closes vechain/veworld-private#296
- Fix pagination dots
[fix_pagination_dots.webm](https://github.com/user-attachments/assets/0fe4a7b5-2c59-484f-a709-f965bcbc70b5)
---
=> Fix pagination

src/Components/Reusable/InAppBrowser/URLBar.tsx, src/Navigation/Stacks/AppsStack.tsx, src/Navigation/Stacks/DiscoverStack.tsx, src/Navigation/Stacks/HistoryStack.tsx, src/Navigation/Stacks/HomeStack.tsx, src/Navigation/Stacks/NFTStack.tsx, src/Navigation/Stacks/SettingsStack.tsx, src/Screens/Flows/App/InAppBrowser/InAppBrowser.tsx
Removed animation on Android to avoid performance issues
---
=> refactor: removed animations on android

src/Hooks/useDappsWithPagination/useAppHubDapps.ts
=> fix(apps): include swaps in defi filter

src/Components/Reusable/BottomSheets/DefaultBottomSheet.tsx
Default bottomsheet with no handle had no top margin
---
=> fix: bottomsheet top margin

src/Screens/Flows/App/HomeScreen/Components/Staking/StakingSection.tsx
Spacing between card was wrong on the homescreen fixed
---
=> Fix :: StarGate card spacing on HomeScreen

src/Hooks/useTransactionFees/useGalacticaFees.spec.ts, src/Hooks/useTransactionFees/useGalacticaFees.ts
Closes vechain/veworld-private#316
Aligned the base gas fee with the SDK config adding a buffer of 12% to avoid rejection when the gas fee are high
N/A
---
=> 316  align gas fee with sdk

.github/workflows/install-build-test-scan.yml
Closes #
Improve the slack E2E failure test messages.
---
=> fix: add more informative slack message for e2e test failures

src/Hooks/useNft/useNFTCollections.tsx, src/Networking/NFT/getNftCollectionMetadata.ts
Closes vechain/veworld-private#305
- Do not fail on totalSupply clause
---
=> fix: do not fail on totalSupply call failure

src/Components/Providers/FeatureFlagsProvider.tsx, src/Components/Providers/InAppBrowserProvider/Components/DappWithDetails.spec.tsx, src/Components/Reusable/NFTMedia/NFTMedia.tsx, src/Screens/Flows/App/ActivityScreen/Components/ActivityBox.spec.tsx, src/Screens/Flows/App/ActivityScreen/Components/ActivityBox.tsx, src/Test/index.tsx
Closes #
- Mock LayoutAnimation to try reducing flakyness
---
=> test: mock LayoutAnimation to try reducing flakyness

src/Hooks/useTransactionScreen/useTransactionScreen.tsx
This PR implements:
- A finally block to ensure loading states are always reset appropriately
- Implement smart loading state management with shouldResetLoading flag (easy to read and understand)
- Fix delegation failure case to properly reset loading state
- Preserve existing behavior for Ledger flow and sendTransactionSafe cleanup
Closes # https://github.com/vechain/veworld-private/issues/179?reload=1?reload=1
-   [x] Documentation, if applicable, has been updated.
---
=> Fix (transaction): Improve loading state management avoiding infinite loop.

.env, src/Constants/Constants/VechainIndexer.ts, src/Networking/API/Types.ts, src/Screens/Flows/App/AppsScreen/Components/Common/VbdCarousel/VbdCarousel.tsx, src/Screens/Flows/App/AppsScreen/Components/Common/VbdCarousel/VbdCarouselBottomSheet.spec.tsx, src/Screens/Flows/App/AppsScreen/Components/Common/VbdCarousel/VbdCarouselBottomSheet.tsx
Closes vechain/veworld-private#331
- Remove B3TR indexer and replace it with the normal indexer
- Fix VBD carousel logic (it was causing an issue where it was collapsing but was popping up again)
---
=> 331 veworld indexer

src/Components/Reusable/GasFeeSpeed/GasFeeTokenBottomSheet.tsx, src/Screens/Flows/App/ActivityScreen/Hooks/useAccountActivities.ts, src/Utils/BalanceUtils/BalanceUtils.spec.ts, src/Utils/BalanceUtils/BalanceUtils.ts
Closes #
- Include dApp login activity in the `dApps` filter
- Fix VTHO getting VET balance when refreshed
- Fix small TS error
[fix_vtho_vet_balance.webm](https://github.com/user-attachments/assets/d7198120-cf62-484f-b1f4-6737ce3ad892)
---
=> 369 bug   244 vtho gets vet balance when vet balance changes

android/app/src/main/AndroidManifest.xml
Implemented Universal Links support on android
N/A
---
=> fix: android manifest to support universal links

src/Screens/Flows/App/BalanceScreen/Header.tsx
Closes vechain/veworld-private#374
- Add testnet selector
---
=> 374 balance   network label

src/Hooks/useUserVeBetterStats/useUserVeBetterStats.spec.ts
Closes #
- Fix broken unit tests relying on date
---
=> fix: fix unit tests

src/Hooks/useSortedTokensByFiatValue/useSortedTokensByFiatValue.ts, src/Screens/Flows/App/BalanceScreen/Components/Tokens/Chart.tsx, src/Screens/Flows/App/BalanceScreen/Components/Tokens/TokenCard.spec.tsx, src/Screens/Flows/App/BalanceScreen/Components/Tokens/TokenCard.tsx
Closes #
- Make sure chart calculations are dynamic
---
=> Updated balance calculations

src/Components/Base/BaseButton.tsx, src/Components/Reusable/DelegationView/SelectedDelegation.tsx, src/Components/Reusable/GasFeeSpeed/EditSpeedSection.tsx, src/Components/Reusable/GasFeeSpeed/GalacticaEstimation.tsx, src/Components/Reusable/GasFeeSpeed/TokenSelector.tsx
Closes # https://github.com/vechain/veworld-private/issues/364
-   [x] Documentation, if applicable, has been updated.
---
=> Fix token selector width

ios/Podfile.lock, ios/VeWorld.xcodeproj/project.pbxproj, package.json
Closes vechain/veworld-private#387
The library wasn't load anymore, probably with some conflicts something was lost, added back the file `CloudKitManager.m` to the file in the build process and everything works fine now
https://github.com/user-attachments/assets/73ff4a85-c1fc-4d35-a13f-01aaf2c411e3
---
=> 387 Fix iCloud not available

src/Screens/Flows/App/AssetDetailScreen/Components/StargateCarouselItem.tsx, src/Screens/Flows/App/HomeScreen/Components/ListsView/Token/VeB3trTokenCard.tsx
Closes #
-   [x] Documentation, if applicable, has been updated.
---
=> Refactor Stargate missing rounded conditional

src/Components/Reusable/SelectAccountBottomSheet/SelectAccountBottomSheet.tsx, src/Hooks/useScrollableBottomSheetList/useScrollableBottomSheetList.ts
Closes vechain/veworld-mobile#348
- Add a bottom padding at the end of the list
- Make the list scrollable
[wallet_switcher_fix_1.webm](https://github.com/user-attachments/assets/b2d03137-6f50-4b95-89ed-3616907bc3a5)
---
=> 348 bug   blank space on wallet switcher component

src/Components/Base/BaseSimpleTabs.tsx, src/Screens/Flows/App/AppsScreen/Components/Favourites/FavouritesV2.tsx, src/Screens/Flows/App/BalanceScreen/Tabs/TabRenderer.tsx
Closes vechain/veworld-private#399
Closes vechain/veworld-private#401
- Fix Favorites cutting off
- Fix padding all around the balance card
---
=> fix: fix paddings + cutoff

src/Navigation/Stacks/HistoryStack.tsx, src/Navigation/Stacks/HomeStack.tsx, src/Screens/Flows/App/ActivityScreen/ActivityScreen.tsx, src/Screens/Flows/App/BalanceScreen/Tabs/Activity/BalanceActivity.tsx
Closes vechain/veworld-private#404
Added navigation to specific activity tab from the "See all" button in the activities section on balance screen
https://github.com/user-attachments/assets/021ec78f-324b-4b6c-b63a-0d3319df204d
---
=> 404 - Enhance "See all" redirect on Balance screen

src/Components/Base/BaseSimpleTabs.tsx, src/Components/Reusable/Tokens/OfficialTokenCard.tsx, src/Screens/Flows/App/BalanceScreen/Tabs/TabRenderer.tsx, src/Screens/Flows/App/ManageTokenScreen/ManageTokenScreen.tsx
Closes vechain/veworld-private#400
- Added back the entry point for the manage token screen
- implemented new logic that shows only selectable tokens in the `Unselected` section and storted them by availability
https://github.com/user-attachments/assets/46936e9e-af89-43cd-9782-2a8efb13aadb
---
=> 400 - Add manage token entry point

src/Components/Reusable/Account/AccountIcon.tsx, src/Components/Reusable/Device/DeviceBox/DeviceBox.tsx, src/Components/Reusable/SelectWatchedAccountBottomSheet/SelectWatchedAccountBottomSheet.tsx, src/Components/Reusable/SelectableAccountCard/SelectableAccountCard.tsx, src/Components/Reusable/WatchedAccountBadge/WatchedAccountBadge.tsx, src/Screens/Flows/App/HomeScreen/Components/AccountCard/AccountCard.tsx, src/Screens/Flows/WalletCreation/ObserveWalletScreen/ObserveWalletScreen.tsx
- Remove old ledger label from SelectableAccountCard
- Update cards with ledger
https://github.com/user-attachments/assets/fbefd193-0096-44b7-8405-3a1f305fb6a2
---
=> fix: remove old ledger label

src/Components/Providers/InAppBrowserProvider/Components/TransactionBottomSheet/ReceiptOutputRenderer/ReceiptOutputRenderer.spec.tsx, src/Hooks/useTotalFiatBalance/useTotalFiatBalance.ts, src/Screens/Flows/App/BalanceScreen/Components/Balance/CurrentBalance.tsx, src/Screens/Flows/App/BalanceScreen/Components/Balance/SlotMachineText.tsx, src/Screens/Flows/App/BalanceScreen/Header.spec.tsx, src/Screens/Flows/App/BalanceScreen/Header.tsx, src/Storage/Redux/Actions/Balances.ts, src/Utils/AddressUtils/AddressUtils.spec.ts, src/Utils/AddressUtils/AddressUtils.ts
Closes vechain/veworld-private#409
- Bump top card fonts
- Update AddressUtils from 6/4 to 5/3 to show 3 characters of the wallet
- Make sure Pull to refresh on homepage updates the top balance too
---
=> fix: top card update

src/Screens/Flows/App/BalanceScreen/Components/Tokens/TokenCard.spec.tsx, src/Screens/Flows/App/BalanceScreen/Components/Tokens/TokenCard.tsx
Closes vechain/veworld-private#410
Made to the ecosystem tokens interactable handling also the bridged tokens
https://github.com/user-attachments/assets/a6b7354d-453a-4eff-8496-c2eb8c4c7047
---
=> 410 - Make ecosystem token card interactable

src/Screens/Flows/App/ActivityScreen/ActivityScreen.tsx, src/Screens/Flows/App/NFT/NFTScreen/Components/NftScreenHeader.tsx
Closes vechain/veworld-private#411
Removed the testnet icon from the pages that aren't homescreen
https://github.com/user-attachments/assets/6a35c4b1-2137-4664-a5f1-792aeed0ba52
---
=> 411 - Remove testnet quick action on screens
